name: jsonlogic
description: jsonlogic is dart implementation of JsonLogic, which applies logic rules on JSON.
version: 2.0.2
homepage: https://github.com/vikesh-raj/jsonlogic

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  flutter_test:
    sdk: flutter

